server:
  port: 8088

spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  profiles:
    active: dev

mybatis-plus:
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 'TRUE'
      logic-not-delete-value: 'FALSE'